apiVersion: v1
description: A Helm chart for Kubernetes that creates a PoC-level deployment of Let's Chat and Mongo.
name: lets-chat
version: 0.1.1
sources:
  - https://github.com/sdelements/lets-chat
  - https://hub.docker.com/r/library/mongo/
maintainers:
  - name: Rick Osowski
    email: osowskeee@gmail.com
